<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CloudNativeKit.Core\CloudNativeKit.Core.csproj" />
    <ProjectReference Include="..\CloudNativeKit.OpenTelemetry\CloudNativeKit.OpenTelemetry.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.EventStore" />
    <PackageReference Include="EventStore.Client.Grpc.Streams" />
  </ItemGroup>
</Project>
