<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CloudNativeKit.Core\CloudNativeKit.Core.csproj" />
    <ProjectReference Include="..\CloudNativeKit.OpenTelemetry\CloudNativeKit.OpenTelemetry.csproj" />
    <ProjectReference Include="..\CloudNativeKit.Persistence.EfCore.Postgres\CloudNativeKit.Persistence.EfCore.Postgres.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
  </ItemGroup>

</Project>
