<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CloudNativeKit.Persistence.EfCore.AzureCosmosDB\CloudNativeKit.Persistence.EfCore.AzureCosmosDB.csproj" />
    <ProjectReference Include="..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>
</Project>